apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: flaky-server-rs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: readiness-example
        kind: flaky-server
    spec:
      containers:
        - name: flaky-server
          image: docker.io/surjection/flaky-server:latest
          ports:
            - containerPort: 8090
          readinessProbe:
            httpGet:
              path: /status
              port: 8090
            initialDelaySeconds: 3
            periodSeconds: 1
