apiVersion: v1
kind: Service
metadata:
  name: readiness-example
spec:
  type: LoadBalancer
  selector:
    app: readiness-example
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
